// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Instance is the predicate function for instance builders.
type Instance func(*sql.Selector)

// Slide is the predicate function for slide builders.
type Slide func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
