database:
  user: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  net: tcp
  addr: ${DATABASE_ADDR}
  dbname: ${DATABASE_DBNAME}
  allowNativePasswords: true
  params:
    parseTime: true
    charset: utf8mb4
    loc: Asia/Kuala_Lumpur
    tls: true

services:
  auth:
    port: 8080
    secretKey: ${AUTH_SECRET_KEY}
    githubClientID: ${GITHUB_CLIENT_ID}
    githubClientSecret: ${GITHUB_CLIENT_SECRET}

  slide:
    port: 8081
