version: "3.8"
services:

  # Auth service
  auth-service:
    image: rust:latest
    container_name: auth-service
#  auth-db:
#    image: postgres:14.1-alpine
#    container_name: auth-db
#    restart: always
#    environment:
#      POSTGRES_DB: auth
#      POSTGRES_PASSWORD: $AUTH_DB_PASSWORD
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
#      interval: 1m
#      timeout: 5s
#      start_period: 10s
#      retries: 3
#    ports:
#      - 5301:5432
