// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/marcustut/fyp/backend/ent/schema"
	"github.com/marcustut/fyp/backend/ent/schema/ulid"
	"github.com/marcustut/fyp/backend/ent/slide"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	slideFields := schema.Slide{}.Fields()
	_ = slideFields
	// slideDescCreatedAt is the schema descriptor for created_at field.
	slideDescCreatedAt := slideFields[2].Descriptor()
	// slide.DefaultCreatedAt holds the default value on creation for the created_at field.
	slide.DefaultCreatedAt = slideDescCreatedAt.Default.(func() time.Time)
	// slideDescUpdatedAt is the schema descriptor for updated_at field.
	slideDescUpdatedAt := slideFields[3].Descriptor()
	// slide.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	slide.DefaultUpdatedAt = slideDescUpdatedAt.Default.(func() time.Time)
	// slideDescID is the schema descriptor for id field.
	slideDescID := slideFields[0].Descriptor()
	// slide.DefaultID holds the default value on creation for the id field.
	slide.DefaultID = slideDescID.Default.(func() ulid.ID)
}
