// Code generated by entc, DO NOT EDIT.

package http

import (
	"time"
)

// Payload of a ent.Slide create request.
type SlideCreateRequest struct {
	Name      *string    `json:"name"`
	CreatedAt *time.Time `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

// Payload of a ent.Slide update request.
type SlideUpdateRequest struct {
	Name *string `json:"name"`
}

// Payload of a ent.User create request.
type UserCreateRequest struct {
	Username  *string    `json:"username"`
	Email     *string    `json:"email"`
	FullName  *string    `json:"full_name"`
	AvatarURL *string    `json:"avatar_url"`
	Bio       *string    `json:"bio"`
	CreatedAt *time.Time `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

// Payload of a ent.User update request.
type UserUpdateRequest struct {
	Username  *string `json:"username"`
	FullName  *string `json:"full_name"`
	AvatarURL *string `json:"avatar_url"`
	Bio       *string `json:"bio"`
}
