// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"time"

	"github.com/marcustut/fyp/backend/ent"
)

type SignInWithEmail struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignInWithUsername struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserWithAuth struct {
	AccessToken string    `json:"access_token"`
	ExpiredAt   time.Time `json:"expired_at"`
	User        *ent.User `json:"user"`
}
